import 'package:desafio_final_camp2024/models/Pokemon_model.dart';

class Autogenerated {
  List<Pokemon>? pokemon;

  Autogenerated({this.pokemon});

  factory Autogenerated.fromJson(Map<String, dynamic> json) {
    return Autogenerated(
      pokemon: List<Pokemon>.from(
          json['pokemon'].map((x) => Pokemon.fromJson(x))),
    );
  }
}