import 'dart:convert';

import 'package:http/http.dart' as http;
import 'package:desafio_final_camp2024/models/Autogenerated_model.dart';

class PokedexService {
  static Future<Autogenerated> buscandoPokemons() async {
    var response = await http.get(
      Uri.parse(
          "https://raw.githubusercontent.com/Biuni/PokemonGO-Pokedex/master/pokedex.json"),
      headers: <String, String>{
        'Content-Type': 'application/json; charset=UTF-8',
      },
    );

    Autogenerated pokemonData = Autogenerated.fromJson(jsonDecode(response.body));
    return pokemonData;
  }
}